// Code generated by main. DO NOT EDIT.

package apis

import (
	"dev.khulnasoft.com/apiserver/pkg/builders"
	"dev.khulnasoft.com/test/apis/test"
	_ "dev.khulnasoft.com/test/apis/test/install" // Install the test group
	testv1 "dev.khulnasoft.com/test/apis/test/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		testv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetTestAPIBuilder(),
	}
}

func GetTestAPIBuilder() *builders.APIGroupBuilder {
	return builders.NewApiGroupBuilder(
		"test.loft.sh",
		"dev.khulnasoft.com/test/apis/test").
		WithUnVersionedApi(test.ApiVersion).
		WithVersionedApis(
			testv1.ApiVersion,
		).
		WithRootScopedKinds(
			"ClusterRole",
		)
}
