@startuml

!theme cloudscape-design
skinparam BackgroundColor lightgray

alt using machine provider
alt machine doesn't exist
DevPod -> Provider: devspace machine create
Provider --> DevPod: machine id
end
DevPod -> Provider: devspace machine start
Provider --> DevPod: machine id
end

DevPod -> Repo: git pull
Repo --> DevPod: source code

alt image not already available
DevPod -> Agent: devspace workspace build
activate Agent
Agent --> ContainerRuntime: build
ContainerRuntime --> Agent: image
Agent --> DevPod: 
deactivate Agent
end

DevPod -> Agent: devspace helper ssh-server --stdio
activate Agent
DevPod -> Agent: devspace agent daemon
DevPod -> Agent: devspace agent workspace up --workspace-info

Agent -> ContainerRuntime: run
ContainerRuntime --> Agent: container id

Agent -> ContainerAgent: devspace helper ssh-server --stdio
activate ContainerAgent

Agent -> ContainerAgent: devspace agent container setup
Agent -> ContainerAgent: devspace agent container credentials-server
alt if EXIT_AFTER_TIMEOUT
Agent -> ContainerAgent: devspace agent container daemon
end

alt if pro user
Agent -> ContainerAgent: devspace agent container setup-loft-platform-access
ContainerAgent -> Platform: Setup pro
Platform --> ContainerAgent: platform creds
end

alt if GIT_SSH_SIGNATURE_FORWARDING
Agent -> DevPod: devspace agent git-credentials
DevPod --> Agent: git creds
end
alt if SSH_INJECT_DOCKER_CREDENTIALS
Agent -> DevPod: devspace agent docker-credentials
DevPod --> Agent: docker creds
end

Agent -> ContainerAgent: Run life cycle hooks

ContainerAgent --> Agent: 
deactivate ContainerAgent
Agent --> DevPod: 
deactivate Agent

alt if using browser based IDE (openvscode, jupyter)
DevPod -> ContainerAgent: devspace ssh --reuse-ssh-auth-sock
end

DevPod -> IDE: Start

alt if using normal IDE (vscode, intilliJ)
IDE -> ContainerAgent: devspace ssh
ContainerAgent --> IDE: ssh close
end

alt if using browser based IDE (openvscode, jupyter)
ContainerAgent -> DevPod: ssh close
end


@enduml
